#!/usr/bin/env python3
"""Ship a DIRECTLY DOWNLOADABLE submission .tif beside the site.

The sibling team sites (e.g. buffedlizard55-lab/5GEMSDOE) publish a ready-made
GeoTIFF under ``docs/downloads/`` so a visitor can right-click and save it with
no JavaScript at all.  14GEMSDOE only had the in-browser builder, so anything
that broke the browser path left the site with **no submission file to
download** — which is exactly what happened on 2026-09-29 (undeclared
``tifBytesNan`` in ``docs/js/site.js``).

This script removes that single point of failure:

    docs/js/payload.js  (the shipped pixel field)
        -> verify pixels_sha256
        -> docs/downloads/<unique name>.tif   float32, EPSG:32611, deflate,
                                               finite [0, 1], no NaN, no NODATA
        -> docs/downloads/<unique name>.tif.sha256
        -> docs/downloads/manifest.json       (hashes + value histogram + note)
        -> rewrite the DIRECT-DOWNLOAD block of docs/index.html

The file it writes carries the SAME pixels as the in-browser build (the browser
uses CompressionStream, this uses zlib, so the containers differ by a few bytes;
the prediction array is identical and verified bit-for-bit here).

Usage:
    python3 scripts/build_site_download.py            # build + patch the site
    python3 scripts/build_site_download.py --check    # verify, write nothing
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import re
import sys
import zlib
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

import rasterio  # noqa: E402
from rasterio.transform import Affine  # noqa: E402

PAYLOAD_JS = REPO / "docs" / "js" / "payload.js"
INDEX_HTML = REPO / "docs" / "index.html"
DOWNLOADS = REPO / "docs" / "downloads"

BEGIN = "<!-- DIRECT-DOWNLOAD:BEGIN (generated by scripts/build_site_download.py) -->"
END = "<!-- DIRECT-DOWNLOAD:END -->"


def decode_payload(path: Path = PAYLOAD_JS) -> tuple[np.ndarray, dict]:
    """Decode docs/js/payload.js (base64 -> zlib -> gems-payload-v1) to a field."""
    src = path.read_text()
    m = re.search(r'GEMS_PAYLOAD_B64\s*=\s*"([^"]+)"', src)
    if not m:
        raise SystemExit(f"{path}: GEMS_PAYLOAD_B64 not found")
    blob = json.loads(zlib.decompress(base64.b64decode(m.group(1))).decode("utf-8"))
    if blob.get("format") != "gems-payload-v1":
        raise SystemExit(f"{path}: unexpected payload format {blob.get('format')!r}")

    rle = blob["rle"]
    values = np.frombuffer(base64.b64decode(rle["values_b64"]), dtype="<f4")
    lengths = np.frombuffer(base64.b64decode(rle["lengths_b64"]), dtype="<i8")
    if values.size != rle["n_runs"] or lengths.size != rle["n_runs"]:
        raise SystemExit(f"{path}: RLE run count mismatch")
    rows, cols = int(blob["rows"]), int(blob["cols"])
    flat = np.repeat(values, lengths)
    want = rows * cols
    if flat.size != want:
        raise SystemExit(f"{path}: decoded {flat.size} px, expected {want} (row-major)")
    field = np.ascontiguousarray(flat.reshape(rows, cols), dtype=np.float32)

    got = hashlib.sha256(field.astype("<f4").tobytes()).hexdigest()
    if got != blob["pixels_sha256"]:
        raise SystemExit(
            f"{path}: pixel hash mismatch — decoded {got}, pinned {blob['pixels_sha256']}")
    return field, blob


def unique_name(blob: dict) -> str:
    """A name that carries its own provenance and cannot collide with another build."""
    stem = re.sub(r"\.tif$", "", str(blob.get("source_file") or "site-build"))
    stem = re.sub(r"[^A-Za-z0-9._-]+", "-", stem).strip("-") or "site-build"
    return f"{stem}_site_{str(blob['pixels_sha256'])[:8]}.tif"


def spatial_profile(blob: dict) -> dict:
    tr = blob["transform"]
    return {
        "driver": "GTiff",
        "height": int(blob["rows"]),
        "width": int(blob["cols"]),
        "count": 1,
        "dtype": "float32",
        "crs": f"EPSG:{int(blob['epsg'])}",
        "transform": Affine(*tr),
        "compress": "deflate",
        "nodata": None,
    }


def write_download(field: np.ndarray, blob: dict, path: Path) -> dict:
    """Write the field as a conformant submission GeoTIFF and verify the round trip."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with rasterio.open(path, "w", **spatial_profile(blob)) as ds:
        ds.write(field.astype(np.float32), 1)

    with rasterio.open(path) as ds:
        back = ds.read(1)
        meta = {
            "shape": [ds.height, ds.width],
            "crs": ds.crs.to_string() if ds.crs else None,
            "transform": list(ds.transform)[:6],
            "res": list(ds.res),
            "count": ds.count,
            "dtype": ds.dtypes[0],
            "compress": ds.profile.get("compress"),
            "nodata": ds.nodata,
        }
    if not np.array_equal(back.view(np.uint32), field.view(np.uint32)):
        raise SystemExit(f"{path}: pixel round-trip is not bit-identical")
    if not np.isfinite(back).all():
        raise SystemExit(f"{path}: non-finite values present")
    if back.min() < 0.0 or back.max() > 1.0:
        raise SystemExit(f"{path}: values outside [0, 1] (min {back.min()}, max {back.max()})")
    return meta


def histogram(field: np.ndarray) -> dict:
    vals, counts = np.unique(field, return_counts=True)
    order = np.argsort(counts)[::-1]
    return {
        "distinct_values": int(vals.size),
        "top": [{"value": float(vals[i]), "pixels": int(counts[i])} for i in order[:8]],
        "positive_pixels": int((field > 0).sum()),
        "nan_pixels": int(np.isnan(field).sum()),
        "total_pixels": int(field.size),
    }


def patch_index(entry: dict, check: bool) -> bool:
    """Rewrite the DIRECT-DOWNLOAD block of docs/index.html.  True if it changed."""
    html = INDEX_HTML.read_text()
    if BEGIN not in html or END not in html:
        raise SystemExit(f"{INDEX_HTML}: DIRECT-DOWNLOAD markers not found — "
                         "restore them before running this script")

    name = entry["file"]
    note = entry["note"]
    new_block = "\n".join([
        BEGIN,
        '<h3 style="margin-top:14px">1 · Download the finished submission file</h3>',
        f'<p><a class="btn primary" href="downloads/{name}" download>'
        f'⬇ Download {name}</a></p>',
        '<p class="kv mono" style="margin:6px 0 2px">'
        f'{entry["bytes"]:,} B · float32 [0,1], no NaN · EPSG:{entry["grid"]["epsg"]} · '
        f'{entry["grid"]["cols"]:,} × {entry["grid"]["rows"]:,} px · '
        f'{entry["histogram"]["positive_pixels"]:,} px above 0.0<br>'
        f'file sha256 <code>{entry["sha256"][:16]}…</code> · '
        f'pixels sha256 <code>{entry["prediction_sha256"][:8]}…</code> · '
        f'<a href="downloads/manifest.json">manifest</a> · '
        f'<a href="downloads/{name}.sha256">checksum</a></p>',
        '<p class="src">This is the real prediction field, not a placeholder: it is the '
        'same pixel array the in-browser builder produces — verified bit-for-bit against '
        '<code>docs/js/payload.js</code> by <code>scripts/build_site_download.py</code> '
        'and <code>tests/test_site_build.py</code>, and passed through the repository\'s '
        'own submission gate (<code>scripts/validate_submission.py</code>). Nothing to '
        'install, no JavaScript required. Click it and go to step 2.</p>',
        '<h4 style="margin:18px 0 4px">Note to paste beside it</h4>',
        f'<pre id="noteTextStatic">{note}</pre>',
        END,
    ])
    out = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), new_block, html, flags=re.S)
    if out == html:
        return False
    if not check:
        INDEX_HTML.write_text(out)
    return True


def prune_stale(keep: Path, check: bool) -> list[str]:
    removed = []
    if not DOWNLOADS.exists():
        return removed
    for p in sorted(DOWNLOADS.glob("*.tif")):
        if p.name != keep.name:
            removed.append(p.name)
            if not check:
                p.unlink()
    return removed


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the shipped download matches the payload; write nothing")
    ap.add_argument("--payload", default=str(PAYLOAD_JS))
    args = ap.parse_args()

    field, blob = decode_payload(Path(args.payload))
    name = unique_name(blob)
    tif = DOWNLOADS / name

    if args.check:
        if not tif.exists():
            print(f"FAIL: {tif} is missing (run scripts/build_site_download.py)")
            return 1
        with rasterio.open(tif) as ds:
            back = ds.read(1)
            shape = (ds.height, ds.width)
            crs = ds.crs.to_string() if ds.crs else None
            tr = list(ds.transform)[:6]
        problems = []
        if shape != (int(blob["rows"]), int(blob["cols"])):
            problems.append(f"shape {shape} != payload grid")
        if crs != f"EPSG:{int(blob['epsg'])}":
            problems.append(f"crs {crs} != EPSG:{int(blob['epsg'])}")
        if not all(abs(a - b) < 1e-9 for a, b in zip(tr, blob["transform"])):
            problems.append(f"transform {tr} != payload {blob['transform']}")
        if not np.array_equal(back.view(np.uint32), field.view(np.uint32)):
            problems.append("pixels differ from the shipped payload")
        if not np.isfinite(back).all():
            problems.append("non-finite values present")
        if back.min() < 0 or back.max() > 1:
            problems.append(f"values outside [0,1]: {back.min()}..{back.max()}")
        man = DOWNLOADS / "manifest.json"
        if not man.exists():
            problems.append("manifest.json missing")
        else:
            meta = json.loads(man.read_text())
            actual = hashlib.sha256(tif.read_bytes()).hexdigest()
            if meta.get("sha256") != actual:
                problems.append("manifest sha256 != file sha256")
        if problems:
            print("FAIL: " + "; ".join(problems))
            return 1
        print(f"PASS — {tif.relative_to(REPO)} matches the shipped payload "
              f"({tif.stat().st_size:,} B, {int((back > 0).sum()):,} px above 0.0)")
        return 0

    meta = write_download(field, blob, tif)
    raw = tif.read_bytes()
    n_pos = int((field > 0).sum())
    note = " · ".join([
        "14GEMSDOE",
        str(blob.get("source_file") or "payload").replace(".tif", ""),
        "site download",
        f"file sha8={hashlib.sha256(raw).hexdigest()[:8]}",
        f"pixels sha8={str(blob['pixels_sha256'])[:8]}",
        f"{n_pos:,} px > 0",
        "finite [0,1] no-NaN",
    ])
    entry = {
        "note": note,
        "file": name,
        "bytes": len(raw),
        "sha256": hashlib.sha256(raw).hexdigest(),
        "prediction_sha256": blob["pixels_sha256"],
        "source_payload": str(Path(args.payload).relative_to(REPO)),
        "source_file": blob.get("source_file"),
        "kind": blob.get("kind"),
        "grid": {"rows": int(blob["rows"]), "cols": int(blob["cols"]),
                 "epsg": int(blob["epsg"]), "res_m": float(blob["res"])},
        "rasterio_profile": {k: (list(v)[:6] if k == "transform" else v)
                             for k, v in meta.items()},
        "histogram": histogram(field),
        "built_by": "scripts/build_site_download.py",
    }
    (tif.with_suffix(".tif.sha256")).write_text(
        f"{entry['sha256']}  {name}\n")
    (DOWNLOADS / "manifest.json").write_text(json.dumps(entry, indent=2, sort_keys=True) + "\n")

    removed = prune_stale(tif, check=False)
    changed = patch_index(entry, check=False)

    print(f"wrote   {tif.relative_to(REPO)}  ({len(raw):,} B, sha256 {entry['sha256'][:16]}…)")
    print(f"pixels  {entry['histogram']['positive_pixels']:,} above 0.0 of "
          f"{entry['histogram']['total_pixels']:,}  (prediction sha256 {entry['prediction_sha256'][:16]}…)")
    if removed:
        print("pruned  " + ", ".join(removed))
    print("index.html direct-download block " + ("updated" if changed else "already current"))

    if blob.get("kind") == "demo":
        print("WARNING: the shipped payload is a DEMO field — do not upload it.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
