#!/usr/bin/env python3
"""Ship a prediction field to the GitHub Pages site as a browser-buildable payload.

The site's "Build submission .tif" button (docs/js/tif_writer.js) writes a
conformant single-band float32 GeoTIFF in the visitor's browser from the pixel
payload embedded in docs/js/payload.js.  This script builds that payload from
any validated submission .tif:

    run-length encoding of the float32 field  (gems-payload-v1)
    + grid metadata + sha256 of the raw float32 pixels
    + the note text to paste into the DrivenData form

Run:
    python3 scripts/build_site_payload.py submissions/GEMS_....tif
    python3 scripts/build_site_payload.py --demo     # the synthetic demo field

The generated docs/js/payload.js records whether the payload is DEMO or REAL;
the site banner renders from that flag.  A demo payload is never presented as
uploadable.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import sys
import zlib
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from gems import raster as gr  # noqa: E402


def rle_encode(arr: np.ndarray) -> dict:
    """Run-length encode a float32 array row-major as (value, runlen) pairs."""
    flat = arr.astype(np.float32).ravel()
    # boundaries where the bit pattern changes (NaN-safe: use byte view)
    raw = flat.view(np.uint32)
    change = np.nonzero(np.diff(raw))[0] + 1
    starts = np.concatenate([[0], change])
    ends = np.concatenate([change, [flat.size]])
    values = flat[starts]
    lengths = (ends - starts).astype(np.int64)
    return {
        "n": int(flat.size),
        "values_b64": base64.b64encode(values.tobytes()).decode("ascii"),
        "lengths_b64": base64.b64encode(lengths.astype(np.int64).tobytes()).decode("ascii"),
        "n_runs": int(values.size),
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("tif", nargs="?", default="")
    ap.add_argument("--demo", action="store_true")
    ap.add_argument("--note", default="")
    ap.add_argument("--out", default="docs/js/payload.js")
    args = ap.parse_args()

    if args.demo:
        cands = sorted(Path("submissions").glob("GEMS_demo_*.tif"))
        if not cands:
            print("no demo submission found — run scripts/make_demo.py first")
            return 2
        tif = cands[-1]
        is_demo = True
    else:
        if not args.tif:
            print("pass a submission .tif path or --demo")
            return 2
        tif = Path(args.tif)
        is_demo = "demo" in tif.name.lower()
        if is_demo:
            print(f"NOTE: {tif.name} looks like a demo artifact; marking payload DEMO")

    arr, meta = gr.read_band(tif)
    pixels_sha = hashlib.sha256(arr.astype(np.float32).tobytes()).hexdigest()

    # normalize: payload stores the field exactly as-is (NaN outside allowed)
    rle = rle_encode(arr)
    payload = {
        "format": "gems-payload-v1",
        "kind": "demo" if is_demo else "real",
        "source_file": tif.name,
        "rows": int(arr.shape[0]),
        "cols": int(arr.shape[1]),
        "epsg": int(str(meta["crs"]).split(":")[-1]) if meta["crs"] and ":" in str(meta["crs"]) else 32611,
        "res": float(meta["res"][0]),
        "transform": list(meta["transform"])[:6],
        "pixels_sha256": pixels_sha,
        "note": args.note or (
            "DEMO payload (synthetic region) — do not upload; rebuild from real data first"
            if is_demo else f"built from {tif.name}"
        ),
        "rle": rle,
    }
    blob = json.dumps(payload, separators=(",", ":")).encode()
    z = zlib.compress(blob, 9)
    b64 = base64.b64encode(z).decode("ascii")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "/* Generated by scripts/build_site_payload.py — do not edit by hand. */\n"
        "/* Source: " + tif.name + "  kind=" + payload["kind"] + "  "
        "pixels_sha256=" + pixels_sha[:16] + "... */\n"
        "(typeof window !== \"undefined\" ? window : globalThis).GEMS_PAYLOAD_B64 = \""
        + b64 + "\";\n"
    )
    print(f"wrote {out} ({len(b64)} b64 chars, {rle['n_runs']} runs, kind={payload['kind']})")
    print(f"pixels sha256 = {pixels_sha}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
