#!/usr/bin/env python3
"""Refresh the public-leaderboard snapshot (the 'current feed').

Fetches the public leaderboard page, parses the standings table, and writes:
    research/leaderboard_snapshot.json   (timestamped, append-only history)
    docs/js/leaderboard.js               (feeds the site's leaderboard page)

The DrivenData leaderboard is public; no credentials are used or needed.
If the network is unavailable the last snapshot stays in place and the script
says so — the site then shows the snapshot's timestamp rather than pretending
to be live.

Usage:  python3 scripts/refresh_leaderboard.py [--url ...]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

SNAPSHOT = Path("research/leaderboard_snapshot.json")
SITE_JS = Path("docs/js/leaderboard.js")
DEFAULT_URL = "https://www.drivendata.org/competitions/306/competition-doe-gems/leaderboard/"

# Our known team/entry identities across the group's submissions (user-reported;
# cross-checked against leaderboard rows on 2026-09-28 — see research/results_ledger.md)
WATCH = ["SDCF9", "wbg1", "smrtdoog5", "extradr19", "smashi34"]


def parse_standings(html: str) -> list[dict]:
    """Parse the public standings from either raw page HTML or markdown text.

    Raw HTML: each row is a <tr> containing /users/<name>/ links and a score
    cell like 0.3168.  Markdown (as returned by text extractors): | #1 | ... | 0.3168 |.
    """
    rows: list[dict] = []
    if "<tr" in html:
        for m in re.finditer(r"<tr[^>]*>(.*?)</tr>", html, flags=re.S | re.I):
            blob = m.group(1)
            if "/users/" not in blob:
                continue
            rm = re.search(r"#(\d+)", blob)
            sm = re.findall(r">\s*([01]\.\d+)\s*<", blob)
            if not rm or not sm:
                continue
            names = re.findall(r"/users/([A-Za-z0-9_\-]+)/", blob)
            display = re.sub(r"<[^>]+>", " ", blob)
            display = re.sub(r"\s+", " ", display).strip()
            rows.append({
                "rank": int(rm.group(1)),
                "users": names,
                "display": display[:120],
                "score": float(sm[-1]),
            })
        return rows

    for m in re.finditer(r"\|\s*#(\d+)\s*\|(.+?)\|\s*([0-9.]+)\s*\|", html, flags=re.S):
        rank = int(m.group(1))
        blob = m.group(2)
        score = float(m.group(3))
        names = re.findall(r"/users/([A-Za-z0-9_\-]+)/", blob)
        display = re.sub(r"<[^>]+>", " ", blob)
        display = re.sub(r"\s+", " ", display).strip()
        rows.append({"rank": rank, "users": names, "display": display[:120], "score": score})
    return rows


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", default=DEFAULT_URL)
    ap.add_argument("--html-file", default="", help="parse a saved HTML file instead of fetching")
    args = ap.parse_args()

    if args.html_file:
        html = Path(args.html_file).read_text(errors="replace")
        fetched = False
    else:
        try:
            import requests
            r = requests.get(args.url, timeout=30, headers={"User-Agent": "14GEMSDOE-status/0.1"})
            r.raise_for_status()
            html = r.text
            fetched = True
        except Exception as e:
            print(f"FETCH FAILED ({type(e).__name__}: {e})")
            if SNAPSHOT.exists():
                print(f"keeping the existing snapshot ({SNAPSHOT})")
                return 0
            print("no snapshot exists yet — cannot build the feed")
            return 1

    rows = parse_standings(html)
    if not rows and fetched:
        print("page fetched but no standings rows parsed — layout change? keeping old snapshot")
        return 1

    snap = {
        "fetched_utc": datetime.now(timezone.utc).isoformat(),
        "source_url": args.url,
        "fetched_live": fetched,
        "n_rows": len(rows),
        "top": rows[:50],
        "watchlist": [r for r in rows if any(w.lower() in
                     (" ".join(r["users"]) + " " + r["display"]).lower() for w in WATCH)],
    }

    history = []
    if SNAPSHOT.exists():
        try:
            history = json.loads(SNAPSHOT.read_text())
            if isinstance(history, dict):
                history = [history]
        except Exception:
            history = []
    history.append(snap)
    SNAPSHOT.write_text(json.dumps(history, indent=2))
    SITE_JS.parent.mkdir(parents=True, exist_ok=True)
    SITE_JS.write_text(
        "/* Generated by scripts/refresh_leaderboard.py — do not edit by hand. */\n"
        "window.GEMS_LEADERBOARD = " + json.dumps(snap) + ";\n"
    )
    print(f"snapshot: {len(rows)} rows, top score {rows[0]['score'] if rows else 'n/a'}")
    print(f"wrote {SNAPSHOT} (history n={len(history)}) and {SITE_JS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
